In [224]:
import pandas as pd#verileri düzenlemek, veriçerçeveleri oluşturmak vb. için kullanılan kütüphane
import numpy as np#büyük sayılar ve hesaplama işlemleri
import matplotlib.pyplot as plt#çizim için
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [225]:
#veriler 2'ye ayrılır:
#1-Sayısal = yaş, kilo, boy gibi sayısal veriler(bu örnek için)
#2-Kategorik = ulke, cinsiyet gibi sayısal olmayan, evet-hayır, tr-fr gibi veriler(bu örnek için)
datas = pd.read_csv('veriler.csv')

In [226]:
print(datas)
datas1 = datas.copy()
datas2 = datas.copy()
datas3 = datas.copy()

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [227]:
#eksik veriler üzerinde işlemler
#eksik verileri yas sütununun ortalaması ile doldurma
mean = datas['yas'].mean()
datas = datas.fillna(mean)
print(datas)

   ulke  boy  kilo    yas cinsiyet
0    tr  130    30  10.00        e
1    tr  125    36  11.00        e
2    tr  135    34  10.00        k
3    tr  133    30   9.00        k
4    tr  129    38  12.00        e
5    tr  180    90  30.00        e
6    tr  190    80  25.00        e
7    tr  175    90  35.00        e
8    tr  177    60  22.00        k
9    us  185   105  33.00        e
10   us  165    55  27.00        k
11   us  155    50  44.00        k
12   us  160    58  28.45        k
13   us  162    59  41.00        k
14   us  167    62  55.00        k
15   fr  174    70  47.00        e
16   fr  193    90  28.45        e
17   fr  187    80  27.00        e
18   fr  183    88  28.00        e
19   fr  159    40  29.00        k
20   fr  164    66  32.00        k
21   fr  166    56  42.00        k


In [228]:
#eksik verileri yas sütununun ortalaması ile doldurma v2
#bu yöntemle sadece dizi üzerinde doldurma işlemi yapılır
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')#nan olan verileri tamamlamak(np.nan), yani nan veriler tamamlanacak
#strategy ile de o nan değerler yerine meanlerin yazılacağı
Yas = datas1.iloc[:,1:4].values#yaş kolonunu çekeceğiz. [:,1:4] = :, tüm satırların gelmesi için. 1:4 kolonları getir
imputer = imputer.fit(Yas[:,1:4])#Öğrenilecek değer(eğitmek için kullanılır). yani kolonların ortalama değerlerini öğrenecek
Yas[:,1:4] = imputer.transform(Yas[:,1:4])#burada ise nan değerlerin yerine değer ataması uygula. Yani ortalamayı yaz nan değerler yerine
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [232]:
#eksik verilerle uğraşmamak için bir diğer yöntem: eğer eksik veri çok yok ve veriye fazla etki etmeyecek gibiyse
#eksik verilerin olduğu satıları komple silebiliriz
#burada 2 tane eksik veri bulunan satır olduğu için o 2 satırı silmemiz bize:
print(datas2.isna().sum() / datas2.shape[0] * 100)# %9'luk bir veri kaybı yaşatacak. O zaman bu 2 satırı silelim
print(datas2)
datas2 = datas2.dropna()
print("\nSatır düşürülmüş hali\n\n", datas2)

ulke        0.0
boy         0.0
kilo        0.0
yas         9.090909
cinsiyet    0.0
dtype: float64
   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

Satır düşürülmüş hali

    ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0 

In [235]:
#Elimizdeki kategorik verileri sayısal değerlere çevirebiliriz
#Ancak buradaki ülke değerlerini sayısal bir veriye çevirdiğimiz zaman sorun çıkabilir: TR=1, US=2, FR=3 diyelim
#buradan baktığımızda us, tr'nin 2 katı vb. bir kıyaslama ortaya çıkıyor veya fr = us+tr gibi bir olay ortaya çıkıyor ancak
#bu değerler arasında böyle bir kıyaslama yapamayız. Onun için sayısal verilere çevirmek çok mantıklı olmaz
#ancak cinsiyeti çevirebiliriz. E=0, K=1 gibi yaparak(kadın-erkek, evet-hayır vb. olduğu için 0-1 kodlama yapılabilir)
#Ülke değerleri için: bir 3'lü doğruluk tablosu yaparız. Ulke tr olan biri için doğruluk tablosunda: tr=1, us=0, fr=0 gibi
#bir değerlendirme yapabiliriz. Us biri için: tr=0, us=1, fr=0; fr biri için: tr=0, us=0, fr=1
#Öncelikle Label Encoding yöntemi: yani Ulkeler

ulke=datas1.iloc[:,0:1].values
le = preprocessing.LabelEncoder()#bu yöntemle farklı değerler için farklı sayı atamaları yapılıyor(bu örnek için tr=1,us=2,fr=0)
ulke[:,0] = le.fit_transform(datas1.iloc[:,0])#burada ise fit ve transform işlemlerini tek seferde yapıyoruz(bir üstte ayrı ayrı yapmıştık)
print("Ulkelere Label Encoder Yapılmış Hali(hepsine sayı verildi)\n",ulke)

#sonra One-Hot Encoding uygulayarak doğruluk tablosu haline getiriyoruz. Ulke kısmı için yapılan işlemler tamam
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()#sonuç numpy array olarak yazılıyor
print("\n\n\nUlkelerin Doğruluk Tablosu Haline Getirilimiş Hali\n", ulke)


#Cinsiyet kısmına da one-hot encoding yapalım. Yalnız burada reshape yapmamızın sebebi:
#normalde bu veriyi (1,n)'lik bir array olarak döndürüyor ancak bizim işlem yapabilmemiz için bu arrayin (n, 1) olması lazım
cinsiyet = datas3.iloc[:, -1].values.reshape(-1, 1)
ohe = preprocessing.OneHotEncoder()
cinsiyet = ohe.fit_transform(cinsiyet).toarray()
print("\n\n\nCinsiyete One-Hot Encoder Yapılmış Hali\n", cinsiyet)







Ulkelere Label Encoder Yapılmış Hali(hepsine sayı verildi)
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]



Ulkelerin Doğruluk Tablosu Haline Getirilimiş Hali
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]



Cinsiyete One-Hot Encoder Yapılmış Hali
 [[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [236]:
#yaptığımız değişiklikleri datas verimize aktarıyoruz(one-hot encoding, label encoding işlemleri ve fit-transform ile yaptığımız
#ortalama alıp nan değerleri doldurma işlemi) bunu dataframe oluşturarak yapıyoruz
#dataframelerin dizilerden farkı, index ve column başlıklarının olması
#Öncelikle ulke işlemlerini dataframe haline getirelim. 22 tane satır olduğu için index=22 yaptık
df = pd.DataFrame(data=ulke, index=range(22), columns=['fr', 'tr', 'usa'])
print("Ulkeler dfsi\n", df)

#Şimdide yas kısmında nan değerleri doldurmuştuk, onların eklendiği sayısal değerler ile bir df oluşturalım
df1 = pd.DataFrame(data=Yas, index=range(22), columns=['boy', 'kilo', 'yas'])
print("\n\nBoy, Kilo, Yas dfsi\n",df1)

#en sonunda ise en sondaki cinsiyet sütununu ele alan bir df oluşturalım
cinsiyet1 = datas1.iloc[:, -1].values
df2 = pd.DataFrame(data=cinsiyet1, index=range(22), columns=['cinsiyet'])
print("\n\nCinsiyet dfsi\n", df2)

#cinsiyet sütununu 1-0 olarak değiştirirsek ortaya çıkacak df:
df3 = pd.DataFrame(data=cinsiyet, index=range(22), columns=['erkek', 'kiz'])
print("\n\nCinsiyet OHE dfsi\n", df3)

#En sonda ise oluşturduğumuz 3 farklı df'yi tek dfde birleştirelim
sonucdf= pd.concat([df, df1, df2], axis=1)#concat df'leri birleştirmemize yarıyor. Axis=1 yapmamızın sebebi ise, yapmadığımız zaman
#alt alta 2 tabloyu yazıyor ancak ilk df'de boy, kilo, yas değerleri yok ama ikinci df'de var, o yüzden o değerlere nan yazar
#aynı şekilde ikinci df'de fr, tr, usa değerleri olmadığı için oralara nan yazar. Axis ile bu kolonları birleştiriyoruz ve
#nan değer yazmasını engelleyip satırları eşliyoruz.

#aşağıda kullanacağımız için tek seferde değil 2 seferde df'leri birleştirelim. Önce ulke ve boy, kilo, yas'ı birleştireceğiz
#cinsiyet olmadan oluşturulan df
sonuc1df = pd.concat([df, df1], axis=1)
print("\n\nUlke ve Boy, Kilo, Yas dfsi\n", sonuc1df)


#sonra ise üstte oluşturduğumuz df ile cinsiyet kolonunu birleştireceğiz
sonuc2df = pd.concat([sonuc1df, df2], axis=1)
print("\n\nBu dfye Cinsiyet eklenmiş halde son df\n", sonuc2df)


sonuc3df = pd.concat([df, df1, df3], axis=1)#Cinsiyet One-Hot Endocing'i için bir df
print("\n\nTek seferde oluşturulmuş df\n", sonucdf)
print("\n\nCinsiyete One-Hot Encoding yaparsak\n", sonuc3df)


Ulkeler dfsi
      fr   tr  usa
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


Boy, Kilo, Yas dfsi
       boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.

In [237]:
#Veri kümesinin eğitim ve test olarak bölünme işlemi
#Amacımız df'yi (ulke, boy, yas, kilo) - (cinsiyet) olarak ayırmak. Verimizi 4 parçaya böleceğiz
#x = bağımsız değişkenler, y = bağımlı değişkenler, train ve test = verinin satır bazlı bölümü. Belli bir satıra kadar olanlar
#train, kalanları test
#bizim x train ve test(bağımsız) değişkenlerimiz = ulke, boy, kilo, yas
#y train ve test(bağımlı) değişkenlerimiz cinsiyet(ohe yapılmamış!)

x_train, x_test, y_train, y_test = train_test_split(sonuc1df, df2, test_size=0.33, random_state=0)
#test_size demek yaklaşık %33'ü test için bölünecek(yani kabaca 7 si) kalanı train için bölünecek
#random_state ise rassal sayı üreticisinin nereden başlayacağı
print(x_train)
print("\n\n", x_test)
print("\n\n",y_train)
print("\n\n",y_test)
#rastgele alınan satırlar ile bağımsız değişkenler gözüküyor ve y değerleri de bu değerlere karşılık gelen bağımlı değişkenler
#test için 8 satır kullanılmış
#yani veriyi öncelikle dikey eksende bağımlı ve bağımsız değişken olarak ayırıyoruz sonra da yatay eksende train ve test olarak ayırıyoruz


     fr   tr  usa    boy   kilo    yas
8   0.0  1.0  0.0  177.0   60.0  22.00
6   0.0  1.0  0.0  190.0   80.0  25.00
16  1.0  0.0  0.0  193.0   90.0  28.45
4   0.0  1.0  0.0  129.0   38.0  12.00
2   0.0  1.0  0.0  135.0   34.0  10.00
5   0.0  1.0  0.0  180.0   90.0  30.00
17  1.0  0.0  0.0  187.0   80.0  27.00
9   0.0  0.0  1.0  185.0  105.0  33.00
7   0.0  1.0  0.0  175.0   90.0  35.00
18  1.0  0.0  0.0  183.0   88.0  28.00
3   0.0  1.0  0.0  133.0   30.0   9.00
0   0.0  1.0  0.0  130.0   30.0  10.00
15  1.0  0.0  0.0  174.0   70.0  47.00
12  0.0  0.0  1.0  160.0   58.0  28.45


      fr   tr  usa    boy  kilo   yas
20  1.0  0.0  0.0  164.0  66.0  32.0
10  0.0  0.0  1.0  165.0  55.0  27.0
14  0.0  0.0  1.0  167.0  62.0  55.0
13  0.0  0.0  1.0  162.0  59.0  41.0
1   0.0  1.0  0.0  125.0  36.0  11.0
21  1.0  0.0  0.0  166.0  56.0  42.0
11  0.0  0.0  1.0  155.0  50.0  44.0
19  1.0  0.0  0.0  159.0  40.0  29.0


    cinsiyet
8         k
6         e
16        e
4         e
2         k
5   

In [223]:
#Öznitelik Ölçekleme
#Normalde bakarsak boylar arasında max-min olarak çok fark var, aynı şekilde yaş ve kiloda da bu durum geçerli
#Biz burada bu aradaki farkı aza indirerek değerleri birbirine yaklaştırmaya, birbirine ölçeklemeye çalışacağız
#Yani farklı dünyalarda olan veriler, aynı dünyaya çekiliyor
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
print(X_train)
print("\n\n", X_test)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.24717129]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.03416189]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178  0.35769504]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.18494855]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.372504  ]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.50305051]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.22171734]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.78438369]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.97193914]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.31549506]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.46628173]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.372504  ]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  2.09727185]
 [-0.63245553 -1.15470054